# Generated by Django 2.2.9 on 2020-01-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200101_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='authors_email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
