# Generated by Django 2.2.3 on 2019-12-19 20:53

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='blurb_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blurb_header_1',
            field=models.CharField(default='My Blurb', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blurb_header_2',
            field=models.CharField(default='My Blurb 2', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blurb_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro_header',
            field=models.CharField(default='Welcome to our website!', max_length=50),
        ),
    ]
