# Generated by Django 2.2.3 on 2019-12-23 18:32

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191219_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_us_button_link',
            field=models.CharField(default='#', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_us_button_text',
            field=models.CharField(default='Learn More', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_us_header',
            field=models.CharField(default='About Us', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_us_sub_header',
            field=models.CharField(default='stuff about us', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_us_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
