# Generated by Django 2.2.3 on 2019-12-24 10:01

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0003_auto_20191223_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=10)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='image_gallery_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image_gallery_title',
            field=models.CharField(default='Gallery', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_firstname',
            field=models.CharField(default='Joe', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_surname',
            field=models.CharField(default='Blogs', max_length=50),
        ),
        migrations.CreateModel(
            name='galleryOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.gallery')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleryOrderable', to='home.HomePage')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'gallerys',
            },
        ),
    ]
