# Generated by Django 2.2.3 on 2019-12-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191226_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='blurb2_buttonText',
            field=models.CharField(default='Find out more', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blurb2_link',
            field=models.CharField(default='#', max_length=50),
        ),
    ]
