# Generated by Django 2.2.3 on 2019-12-27 10:42

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191227_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='iconItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('text', wagtail.core.fields.RichTextField(blank=True)),
                ('linkText', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='icon_list_header',
            field=models.CharField(default='Our approach', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='enumerated_list_header',
            field=models.CharField(default='Our approach', max_length=50),
        ),
        migrations.CreateModel(
            name='iconListOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('iconItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.iconItem')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='iconListOrderable', to='home.HomePage')),
            ],
            options={
                'verbose_name': 'Icon List item',
                'verbose_name_plural': 'Icon List items',
            },
        ),
    ]
