# Generated by Django 2.2.3 on 2019-12-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20191227_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='about_us_button_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about_us_button_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about_us_header',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about_us_sub_header',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about_us_text',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='icon_list_header',
            field=models.CharField(default='Our Services', max_length=50),
        ),
    ]
