# Generated by Django 2.2.3 on 2019-12-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20191228_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='client_addressLine1',
            field=models.CharField(default='Line 1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='client_addressLine2',
            field=models.CharField(default='Line 2', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='client_country',
            field=models.CharField(default='Country', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='client_county',
            field=models.CharField(default='County', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='client_email',
            field=models.CharField(default='joe@bloggs.com', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='client_moblie',
            field=models.CharField(default='01234 456789', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='client_phone',
            field=models.CharField(default='01234 456789', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='client_postcode',
            field=models.CharField(default='XX00 0XX ', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='client_town',
            field=models.CharField(default='Town', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_contact_form',
            field=models.BooleanField(default=True),
        ),
    ]
