# Generated by Django 2.2.3 on 2019-12-28 09:57

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20191228_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='footer_info',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_info_title',
            field=models.CharField(default='About', max_length=50),
        ),
    ]
