# Generated by Django 2.2.3 on 2019-12-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20191228_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_blurb',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_second_blurb',
            field=models.BooleanField(default=True),
        ),
    ]
