# Generated by Django 2.2.3 on 2019-12-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20191228_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='blurb_header',
            field=models.CharField(default='Blurb', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='enumerated_list_header',
            field=models.CharField(default='Approach', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='icon_list_header',
            field=models.CharField(default='Services', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='second_blurb_header',
            field=models.CharField(default='Blurb 2', max_length=50),
        ),
    ]
