# Generated by Django 2.2.9 on 2019-12-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_socialmediaitem_socialmediaorderable'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_blurb_in_navigation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_contact_in_navigation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_enumerated_list_in_navigation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_gallery_in_navigation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_icon_list_in_navigation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_second_blurb_in_navigation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_testimonials_in_navigation',
            field=models.BooleanField(default=True),
        ),
    ]
