# Generated by Django 2.2.9 on 2019-12-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20191228_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='show_blurb_in_navigation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='show_second_blurb_in_navigation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='show_testimonials_in_navigation',
            field=models.BooleanField(default=False),
        ),
    ]
