# Generated by Django 2.2.3 on 2019-12-29 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0019_auto_20191228_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='primary_colour',
            field=models.CharField(default='#f37e77', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='secondary_colour',
            field=models.CharField(default='#ffffff', max_length=50),
        ),
    ]
