# Generated by Django 2.2.3 on 2019-12-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20191229_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='blurb_buttonText',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='blurb_link',
        ),
    ]
