# Generated by Django 2.2.3 on 2020-01-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20191229_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='blog_title',
            field=models.CharField(default='Blogs', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='preview_word_limit',
            field=models.IntegerField(default=140),
        ),
    ]
