# Generated by Django 2.2.9 on 2020-01-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20200101_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='medium_username',
            field=models.CharField(default='About', max_length=50),
        ),
    ]
