# Generated by Django 2.2.9 on 2020-01-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_homepage_medium_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='preview_word_limit',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='medium_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
