# Generated by Django 2.2.9 on 2020-01-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20200105_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='blog_title',
            field=models.CharField(blank=True, default='Blogs', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='blurb_header',
            field=models.CharField(blank=True, default='Blurb', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='blurb_subheader',
            field=models.CharField(blank=True, default='this is a blurb', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_addressLine1',
            field=models.CharField(blank=True, default='Line 1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_addressLine2',
            field=models.CharField(blank=True, default='Line 2', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_country',
            field=models.CharField(blank=True, default='Country', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_county',
            field=models.CharField(blank=True, default='County', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_firstname',
            field=models.CharField(blank=True, default='Joe', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_moblie',
            field=models.CharField(blank=True, default='01234 456789', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_organisationName',
            field=models.CharField(blank=True, default='My Company', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_phone',
            field=models.CharField(blank=True, default='01234 456789', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_postcode',
            field=models.CharField(blank=True, default='XX00 0XX ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_surname',
            field=models.CharField(blank=True, default='Blogs', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_town',
            field=models.CharField(blank=True, default='Town', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='contact_subtitle',
            field=models.CharField(blank=True, default='Get in contact', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='contact_title',
            field=models.CharField(blank=True, default='Contact', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='enumerated_list_header',
            field=models.CharField(blank=True, default='Approach', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_info_title',
            field=models.CharField(blank=True, default='About', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='icon_list_header',
            field=models.CharField(blank=True, default='Services', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='second_blurb_buttonText',
            field=models.CharField(blank=True, default='Find out more', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='second_blurb_header',
            field=models.CharField(blank=True, default='Blurb 2', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='second_blurb_subheader',
            field=models.CharField(blank=True, default='My Second Blurb 2', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='testimonials_header',
            field=models.CharField(blank=True, default='Testimonials', max_length=50),
        ),
    ]
