# Generated by Django 2.2.3 on 2020-01-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20200105_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='medium_blog_display_limit',
            field=models.IntegerField(blank=True, default=6),
        ),
    ]
