# Generated by Django 2.2.3 on 2020-01-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_homepage_medium_blog_display_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='client_addressLine1',
            field=models.CharField(blank=True, default='Line 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_addressLine2',
            field=models.CharField(blank=True, default='Line 2', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_country',
            field=models.CharField(blank=True, default='Country', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_county',
            field=models.CharField(blank=True, default='County', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_moblie',
            field=models.CharField(blank=True, default='01234 456789', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_phone',
            field=models.CharField(blank=True, default='01234 456789', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_postcode',
            field=models.CharField(blank=True, default='XX00 0XX ', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_town',
            field=models.CharField(blank=True, default='Town', max_length=50),
        ),
    ]
