# Generated by Django 2.2.9 on 2020-01-19 08:43

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20200106_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='secondary_colour',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='primary_colour',
            field=colorfield.fields.ColorField(default='#f37e77', max_length=18),
        ),
    ]
