# Generated by Django 2.2 on 2020-01-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20200119_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='custom_css',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='homepage',
            name='custom_html',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='homepage',
            name='custom_javacript',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
