# Generated by Django 2.2 on 2020-01-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20200119_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='custom_css',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='custom_html',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='custom_javacript',
            field=models.TextField(blank=True),
        ),
    ]
